/*
@author Liquibase
@version 1.0
@date 4/8/2025
@description Oracle CREATE (OR REPLACE) TYPE statements must terminate with "/" character.

Copyright (c) 2024 Liquibase, Inc. All Rights Reserved.

Sample Passing Script
-------------------------------------------------------------------------------
CREATE TYPE customer_typ_demo AS OBJECT
    ( customer_id        NUMBER(6)
    , cust_first_name    VARCHAR2(20)
    , cust_last_name     VARCHAR2(20)
    ) ;
/


Sample Failing Script
-------------------------------------------------------------------------------
CREATE OR REPLACE TYPE customer_typ_demo AS OBJECT
    ( customer_id        NUMBER(6)
    , cust_first_name    VARCHAR2(20)
    , cust_last_name     VARCHAR2(20)
    ) ;


Instructions
-------------------------------------------------------------------------------
1) Add script to Rules -> SqlRules folder.
2) To test outside of pacakger run: hammer runRules <path to script or folder> 

*/

package com.datical.hammer.core.sqlrules.CreateTypeStatementsNeedSlash

import java.util.regex.Matcher;
import java.util.regex.Pattern;

import com.datical.db.project.Project;
import com.datical.hammer.core.rules.Response;
import com.datical.hammer.core.rules.Response.ResponseType;
import com.datical.hammer.core.rules.WithComments;
import com.datical.hammer.core.rules.WithoutComments;


/* @return false if validation fails; true otherwise */
function boolean validateTerminator(String sql)
{
    System.out.println("Validation called: Create Type Terminator");
	
	// System.out.println("SQL: " + sql);
	
	// Regex is checking for a CREATE (OR REPLACE) TYPE .... ; statement.
	// It additionally pulls in Matcher Group 2 which needs to be a "/" character.
	
	final String regex = "create\\s+(or\\s+replace\\s+|)type\\s+.*?;\\s*(.)";
	final Pattern pattern = Pattern.compile(regex, Pattern.MULTILINE | Pattern.CASE_INSENSITIVE | Pattern.DOTALL);
    final Matcher matcher = pattern.matcher(sql);
	
	while (matcher.find()) {
	
		// Matcher Group 0 will be the CREATE TYPE statement.
		// Matcher Group 2 should be the "/" character.
		
		if (!(matcher.group(2)).equals("/")) {
			return true;
		}		
    }
    return false;
}

rule "Create Type statements must end with slash"
when
		woc : WithoutComments(validateTerminator(getText().toLowerCase()))
then
		String errorMessage = "CREATE TYPE scripts must end with a termination character (/) in the Sql Script (" + woc.getSqlFile().getName() + ")";  
		insert(new Response(ResponseType.FAIL, errorMessage, drools.getRule().getName()));
end